#!/bin/sh

# This is a bash script that should pull the latest machine names from munki report and write new manifests using them and the IITS baseline

# If needed, we can set this to listen to the 'munkireport' table in the DB.. it needs to tell us when there's an update. 
# - no code here, yet. It's unneccessary for the script's current purpose, as the cp -u command ought to prevent overwrites, and this can be run by Cron at 1 min intervals, etc...


# In order to figure out which machine we should make a new ID for, we'll look at the current status of the manifests:
lastnum=`mysql -u[NAME] -p[PASS] -s -N -e "Use [Munki Report DB]; SELECT MAX(id) FROM machine"`
echo $lastnum

# You'll need to put a while loop and an if loop to get the increment thing to work, and it's unneccessary now. 

id=`mysql -u[USER] -p[PASS] -s -N -e "Use munkireport; SELECT hostname FROM machine WHERE ID=' "$lastnum" '"`

#second, let's make a file. I've set this to not overwrite anything that already exists, which should cause the script to stop here if it's hitting the same thing again. This a quick, dirty fix. 

cp -u [LOCATION of]munki_repo/manifests/[TEMPLATE] [LOCATION of]munki_repo/manifests/"$id"

#that's it!




